image: docker:24.0.5

pipelines:
  branches:
    main:
      - step:
          name: Build frontend
          size: 2x
          services:
            - docker
          caches:
            - node
          script:
            - echo "Install Node.js"
            - apk add --no-cache nodejs npm

            - echo "Install dependencies"
            - npm ci

            - echo "Build frontend"
            - npm run build

            - echo "Login to Docker Hub"
            - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

            - echo "Build lightweight Docker image"
            - export DOCKER_BUILDKIT=0
            - docker build -t $DOCKER_REPO:$BITBUCKET_COMMIT .

            - echo "Push Docker image"
            - docker push $DOCKER_REPO:$BITBUCKET_COMMIT
