image: node:20-alpine

pipelines:
  branches:
    main:
      - step:
          name: Build frontend
          size: 2x
          caches:
            - node
          script:
            - echo "Install dependencies"
            - npm ci

            - echo "Build frontend"
            - npm run build

            - echo "Login to Docker Hub"
            - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

            - echo "Build lightweight Docker image"
            - docker build -t $DOCKER_REPO:$BITBUCKET_COMMIT .

            - echo "Push Docker image"
            - docker push $DOCKER_REPO:$BITBUCKET_COMMIT